apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: prowlarr-postgres
    namespace: downloads
stringData:
    POSTGRES_URL: ENC[AES256_GCM,data:eL7Wv3Snhe3tgfCq3lOJ/LcuqY57e8JRQwZRJV7zGal4q5/FXH3EqD/LcIHsncHa4xNadye5H7xfK9NEdfZDcnOwJQk=,iv:8vJ9h2riFotsozq4U9XLkfbEgnr4Qk1AUt9PM0o5cTI=,tag:+eQjHopg+AtmPwVOIcrcKA==,type:str]
    POSTGRES_LOG_URL: ENC[AES256_GCM,data:L0lZQx3tAYhZ0yY/DBFhLGLERhRIiWhrr3g8/8u9ryTCduXv7/ZFE3DiNpReLLBhAX15VnX29aefZtm0Fmwoor/s/dJKBx8s,iv:lOKBZH6DDdpv/GDDUTlD8E+pshHHITpOc9Kxp9zx/b4=,tag:pCEKgS+AayAf8hnC0Z037g==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:JWjj7Vmp0VWe/A/lJuH1PtfwI/o=,iv:IEN5jSltASw6peTRfGVrF8oHxyFA1s2yD8AX6VZgbo0=,tag:8fLkRLwt4lbi0LFWYKHHBg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:3gddwxWfEuE=,iv:E9CdhWZbsskreGOW2LsyAlCeajBR5bJUmpWhnDsSRlU=,tag:IwMphThWAj23AZNuhsT25g==,type:str]
    POSTGRES_LOG_DB: ENC[AES256_GCM,data:MRWKn2XvMLzKbigV,iv:ZcA7vW1PFgzCi7WVavKwb5W1HfWVMqTNa/r/P2k08uU=,tag:QkG7GDa9Lz3TqXwfgb4G6g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:oLz5ym1snq0=,iv:SI6FZxIcpNYsUHSwwfxXtCJv6E23A04xLhdvxt3eyeM=,tag:m64jVJxVa4KXcfKa7TmzdQ==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:6jN98yvvv5qkShsgQMBMPQ==,iv:gRoM0elsvhGj9f47+Vignz673FefxZqEG5GdRQE+V7M=,tag:p7F3q8N/dpb4roSuZr5bmg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:uXiwQhO0u9+DUh5J3vdkig==,iv:g5UOUVl/2g1h63HRVEIb0TAl6v6kqJ6dAlsM28nFrYk=,tag:1XZ0mF7iZbKkdIn+NZhojQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfn3vxpsgm49ljgs8kxevga9makhh9aply6ddgf9wplsfuwpcv2qzmqatc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SEJKZ2E0am5pK2p5Snlt
            Z0xZUTRoK3FnUzM3akhkajYwTXhRbTlOZEhzCkNQSENPN1VXWGVZeW9ULzh5UUtG
            cm85UUZVcEQ5OGxUcVlNd1laS3RjazQKLS0tIHB1MGRSMEVtbEtBbTdXUHhTWVdP
            K1RTUmVFaTk4dUJxUG5Ed3FKa2dnOVUK9StVLWh/13uRkyeOvzwwuUNZVwNHP4N1
            wvhAKN8jYkzI+EmCaLOnfrUNAzJqVDs9tC0Tj30YJ8j5eHgrQg04zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-29T14:46:00Z"
    mac: ENC[AES256_GCM,data:Jk8/K7MT7NKOPwmx3zrpoymeAXpq3pQXx9/KxuXq7UBBiFEXVr4RoLO57Q65wQpxsALJ1EOE00qfCv06hX6Yz6d8+BT6VsmGBuhA6xIeFJ/M4kAKNQQC8hLPtc5BaFgnksO44XXN44kJIfGbIH7H94HWYWCBADsZsspSOR3R2ig=,iv:WB8jEijTKHWbPrSVZyeRxtBgK6JUUczftxWGlRPdvgg=,tag:KxPkIoRNSkznflEVKlL7Kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
